spring:
  message:
    basename: messages
# Swageer 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa



management:
  endpoints:
    web:
      exposure:
        include: "*"

